---

- name: Download Kolab Repo
  get_url:
    url: "{{ kolab_repo_url }}" 
    dest: "{{ kolab_repo_dest }}"


- name: Import GPG Key
  rpm_key:
    state: present
    key: "{{ kolab_repo_key }}"

- name: Install Packages
  yum:
    name: "{{ kolab_packages }}"
    state: present

- name: Create Setup Config File
  template:
    src: templates/kolab.conf.j2
    dest: "{{ kolab_setup_tmp }}"

- name: Setup with Default Settings
  command: "setup-kolab --config {{ kolab_setup_tmp }} --without-ldap --with-openldap --mysqlserve^Cnew -q -e"

- name: Create Config File
  template:
    src: templates/kolab.conf.j2
    dest: "{{ kolab_conf_path }}"

- name: Delete Setup Config File
  file:
    path: "{{ kolab_setup_tmp }}"
    state: absent

- name: Setup Firewall Services
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  with_items:
  - 465/tcp
  - 25/tcp
  - 80/tcp
  - 443/tcp

- name: Reload Firewalld
  systemd:
    name: firewalld
    state: restarted

- name: Load LDAP Schema
  command: ldapadd -x -H "{{ kolab_ldap_uri }}" -D "{{ kolab_ldap_binddn }}"  -w "{{ kolab_ldap_bindpw  }}" -f {{ kolab_ldap_schema }} 


